#Spring config
spring:
  application:
    name: config-server
  #Cloud config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/italohonorato/config-server
          default-label: master
          searchPaths: eureka-server
          clone-on-start: true
#App Server Port
server:
  port: 4444